url: https://liet.rq.lt/
DefaultContentLanguage: lt
title: lietuvybė.lt
description: Lietuvių kalba informacinėse technologijose
theme: mainroad
permalinks:
    page:
        /: /:slug/
#uglyURLs: true # use .html suffix instead of a trailing slash
markup:
    goldmark:
        renderer:
            unsafe: true # Allow HTML tags in MarkDown
        parser:
            attribute:
                block: true
params:
    description: Lietuvių kalba informacinėse technologijose
    subtitle: Lietuvių kalba informacinėse technologijose
    copyright: Lietuvybė.lt komanda
    mainSections: [ ]
    dateFormat: :date_long
    post_meta:
        - date
    customCss: [ 'css/custom.css' ]
    style:
        vars:
            highlightColor: "#a1c442"
